# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: freshli_agent.proto for package 'com.corgibytes.freshli.agent'

require 'grpc'
require 'freshli_agent_pb'

module Com
  module Corgibytes
    module Freshli
      module Agent
        module Agent
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'com.corgibytes.freshli.agent.Agent'

            rpc :DetectManifests, ::Com::Corgibytes::Freshli::Agent::ProjectLocation, stream(::Com::Corgibytes::Freshli::Agent::ManifestLocation)
            rpc :ProcessManifest, ::Com::Corgibytes::Freshli::Agent::ProcessingRequest, ::Com::Corgibytes::Freshli::Agent::BomLocation
            rpc :RetrieveReleaseHistory, ::Com::Corgibytes::Freshli::Agent::Package, stream(::Com::Corgibytes::Freshli::Agent::PackageRelease)
            rpc :GetValidatingPackages, ::Google::Protobuf::Empty, stream(::Com::Corgibytes::Freshli::Agent::Package)
            rpc :GetValidatingRepositories, ::Google::Protobuf::Empty, stream(::Com::Corgibytes::Freshli::Agent::RepositoryLocation)
            rpc :Shutdown, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
