# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freshli_agent.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("freshli_agent.proto", :syntax => :proto3) do
    add_message "com.corgibytes.freshli.agent.ProjectLocation" do
      optional :path, :string, 1
    end
    add_message "com.corgibytes.freshli.agent.ManifestLocation" do
      optional :path, :string, 1
    end
    add_message "com.corgibytes.freshli.agent.ProcessingRequest" do
      optional :manifest, :message, 1, "com.corgibytes.freshli.agent.ManifestLocation"
      optional :moment, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "com.corgibytes.freshli.agent.BomLocation" do
      optional :path, :string, 1
    end
    add_message "com.corgibytes.freshli.agent.Package" do
      optional :purl, :string, 1
    end
    add_message "com.corgibytes.freshli.agent.PackageRelease" do
      optional :version, :string, 1
      optional :released_at, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "com.corgibytes.freshli.agent.RepositoryLocation" do
      optional :url, :string, 1
    end
  end
end

module Com
  module Corgibytes
    module Freshli
      module Agent
        ProjectLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.corgibytes.freshli.agent.ProjectLocation").msgclass
        ManifestLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.corgibytes.freshli.agent.ManifestLocation").msgclass
        ProcessingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.corgibytes.freshli.agent.ProcessingRequest").msgclass
        BomLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.corgibytes.freshli.agent.BomLocation").msgclass
        Package = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.corgibytes.freshli.agent.Package").msgclass
        PackageRelease = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.corgibytes.freshli.agent.PackageRelease").msgclass
        RepositoryLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.corgibytes.freshli.agent.RepositoryLocation").msgclass
      end
    end
  end
end
